### ISSUE TITLE
Allow positioning vertices with numeric values

### ISSUE THREAD

**Issue by smaren** [EsotericSoftware/spine-editor#530] opened 2020-02-11 10:39 UTC
If you have for instance a path attachment, it would often be beneficial to set numeric positions for vertices. You may want the path to go from `(0, 0)` to `(100, 0)`. If a vertex position could be set numerically, that would be trivial to do.

**Comment by erikari** [comment] 2020-02-13 15:11
Duplicate of #77.

**Closed** 2020-02-13 15:11 UTC
