### ISSUE TITLE
Add a warning when changing the editor version to the newer `Latest X.X`

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#715] opened 2022-10-23 07:07 UTC
Selecting a newer version of `Latest X.X` in the settings window in an older version of the Spine editor may cause it to change to an unintended version. For example, if you choose `Latest 3.8` to switch the editor version to 3.8.99, the setting will be converted `Latest stable` in 3.8, so the latest stable version will be launched on the next run unintentionally. This was previously reported in the following issue:
https://github.com/EsotericSoftware/spine-editor/issues/622

Similar cases have occurred from 4.0 to 4.1. Choosing `Latest 4.1` on the version select box in 4.0 would be changed to `Latest beta` after restarting Spine. This has been reported on the following forum post:
http://esotericsoftware.com/forum/I-don-t-want-latest-beta-just-4-1-18143

It is possible that such discrepancies will occur in the future version, so we should improve it, such as showing a warning to update from the Spine launcher as much as possible when updating to a new version, such as updating from 4.1 to 4.2.

**Comment by NathanSweet** [comment] 2022-10-24 01:41
#622 was about opening settings in 3.8.99 and saving the settings. I don't think it's related to the forum post and it was fixed in launcher 4.1.03.

If there is an issue here, we need repro steps. It seems the issue is this:

1. Run 4.0 or 4.1.
2. Open the settings dialog, choose `Latest 4.1` (or leave it as the if it is already), save settings.
3. Close the editor.
4. Start the launcher.

Expected: The version to be `Latest 4.1`.
Actual: The version is `Latest beta`.

Probably something is confused by both `Latest 4.1` and `Latest beta` both being the same version until the 4.2 beta starts.

**Comment by NathanSweet** [comment] 2022-10-24 02:04
Fixed in 4.1.15.

We can't fix it in 4.0, but it's only an issue when the latest stable and latest beta are the same version. That usually isn't a very long time, but with 4.2 the complexity of physics is taking longer for the beta to start.

**Closed by NathanSweet** 2022-10-24 02:04 UTC
Labels: bug
