### ISSUE TITLE
Photoshop To Spine script to consider clipping masks

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#559] opened 2020-05-21 16:50 UTC
**Problem 1: Clipping masks applied to layers**
Currently the Photoshop to Spine script doesn't apply Clipping Masks to the layer they are clipped to, but it exports them as separate layers. They are exported correctly if they are placed inside a [merge] tag.

Possible hint to a solution strictly for this case: 
In Photoshop there is a command called `Merge Clipping Mask` that appears by right-clicking on a layer that serves as the base for layers clipped above it. This command will merge the clipping mask and the layer into one layer. This could help automatically apply clipping masks to layers.

**Problem 2: Clipping masks applied to groups**
Clipping masks can also be applied to groups. In this case there is no option to merge the clipping mask specifically.

**Desired requirements for a solution:**
- don't export the clipping layer on its own 
- only apply the clipping to the contents of the folder it is clipped to
- apply the clipping mask for each layer or folder inside the main folder respecting the blending mode (e.g. multiply)
- if the folder, or its subfolders, has a [merge] tag, apply the merge tag first, then apply the clipping mask to it.
- optionally the layer could be marked with an `[adjust]` tag in case the script has a hard time finding clipping masks (personally I don't think that's necessary)

**Example:**
Photoshop structure: 
![](https://www.erikari.it/uploads/868-ATJ3.png)
Current result:
![](https://www.erikari.it/uploads/869-sHef.png)
Expected result:
![](https://www.erikari.it/uploads/871-4KBW.png)

An example of layer that does a similar behavior with the script:

> Adjustment layers are automatically applied to the generated images, without having to apply or merge them to each layer below them.

**Test PSD download:**
https://www.erikari.it/uploads/870-clipping-mask-multiply-test.psd 

**Related thread:**
http://esotericsoftware.com/forum/Just-an-idea-about-a-new-tag-for-the-PS-export-script-14004

**Comment by davidetan** [comment] 2024-04-03 13:37
Closing because this already works as intended in PS script.
Moreover, the same result can be obtained by using the `[overlay]` tag.

However, we're planning to make the PS script work exactly like the new Import PSD feature in Spine 4.2 (still beta at the time of this writing).
This means that utilizing a clipping mask on a group will result in behaviour equivalent in having the `[merge]` tag on the group.
Still, the desired result of this issue can be obtained by using the `[overlay]` tag.

**Closed by davidetan** 2024-04-03 13:37 UTC
Labels: enhancement
