### ISSUE TITLE
Add a feature to divide mesh edges

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-editor#716] opened 2022-10-26 05:49 UTC
There is the Generate tool in the edit mode of meshes, but it removes the weights of all vertices. It would be useful to have the feature to add a vertex on the middle of  selected edges without reset weights settings.

Related post:
http://esotericsoftware.com/forum/Weights-feature-improvement-18162

**Comment by NathanSweet** [comment] 2024-03-20 02:50
Closing as duplicate of #313.

**Closed by NathanSweet** 2024-03-20 02:50 UTC
