### ISSUE TITLE
Masking areas

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-editor#84] opened 2016-08-05 07:37 UTC
User request per e-mail (`Put masking function`). Add the ability to define masking areas behind which nothing should be drawn. This is both an editor and runtime feature, the latter making it somewhat hard to implement. The only strategy that comes to mind at the moment is to use the stencil buffer, but that's highly runtime dependent and may not mix well with the rest of the rendering infrastructure of the engine.

**Comment by NathanSweet** [comment] 2016-08-05 15:53
Duplicate of #32.

**Closed by NathanSweet** 2016-08-05 15:53 UTC
Labels: editor, enhancement
