### ISSUE TITLE
Copy/move bones and other items from one skeleton to another

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-editor#72] opened 2016-07-08 01:29 UTC
http://esotericsoftware.com/forum/Transfer-bones-from-a-skeleton-to-another-6655

**Comment by mishaelfedorov** [comment] 2016-09-21 16:48
+1

**Comment by NathanSweet** [comment] 2016-10-20 20:12
Duplicate of #36

**Closed** 2016-10-20 20:12 UTC
Labels: editor
