### ISSUE TITLE
It would be nice to be able to specify one specific animation when exporting a sequence.

### ISSUE THREAD

**Issue by Fraggle** [EsotericSoftware/spine-editor#116] opened 2016-09-29 14:41 UTC
Hi,

Right now, it's "current" or "all", but when we have a pipeline to generate assets, we might want to generate an sequence with a specific name and not rely on the animator leaving the .spine file on the correct sequence.

Thanks,

Seb

**Comment by NathanSweet** [comment] 2016-11-03 23:40
I agree this is needed, but closing as dupe of #73

**Closed** 2016-11-03 23:40 UTC
