### ISSUE TITLE
Circular region selection tool for mesh editor

### ISSUE THREAD

**Issue by windship** [EsotericSoftware/spine-editor#140] opened 2016-12-09 08:18 UTC
https://knowledge.autodesk.com/support/3ds-max/learn-explore/caas/CloudHelp/cloudhelp/2016/ENU/3DSMax/files/GUID-E371C8DA-9664-4284-9AFA-826EF4544144-htm.html

This kind of circular region selection tool will be easier to select radial layout of vertex. I hope you will add this select tool for mesh editor also, not only marquee one. Thanks.

**Comment by NathanSweet** [comment] 2016-12-09 08:19
Duplicate of #126. Please do a search before opening issues.

**Closed by NathanSweet** 2016-12-09 08:19 UTC
