### ISSUE TITLE
Vertex manipulation: numeric coordinate entry

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#333] opened 2018-03-26 10:06 UTC
As pointed out in [this topic](http://esotericsoftware.com/forum/Precise-clipping-mask-10108) it would make sense to be able to manually edit the position and/or rotation of a single vertex, may it be from a clipping mask, a mesh, or path.

**Comment by pharan** [comment] 2018-03-26 11:49
This has been requested a a number of times before. Was there really no existing issue?

**Comment by NathanSweet** [comment] 2019-04-12 17:57
Duplicate of #77.

**Closed by NathanSweet** 2019-04-12 17:57 UTC
Labels: enhancement
