### ISSUE TITLE
[issue] New keyframes don't always get default curve

### ISSUE THREAD

**Issue by bencresty** [EsotericSoftware/spine-editor#679] opened 2022-07-31 08:33 UTC
New keyframes don't get the curve as set in the settings as default curve::

When having default curve on 'Bezier' we don't get the default curve on new keyframes anymore if one of the existing keyframes was changed to another curve type. Than we get that curve type. It doesn't matter which keyframe we changed, all new keyframes now suddenly get that curve type. That's obviously not what we want as we set the default curve type to be used for new keyframes.

Spine 4.1.06

**Comment by NathanSweet** [comment] 2022-08-07 20:48
When a key is set between existing keys, Spine does "curve splitting" where the interpolated value on the existing curve is used and the new key is assigned the same curve type.

For example:
![](http://n4te.com/x/5168-YWJx.png)
Becomes:
![](http://n4te.com/x/5169-wUIn.png)

Or:
![](http://n4te.com/x/5170-yZSA.png)
Becomes:
![](http://n4te.com/x/5171-1a1m.png)

Adding the new key in this way does not change the animation at all. We find this most often matches what the user wants.

The default curve type setting is only used when curve splitting can't be done:

> The type of curve to use when it can't be determined from the surrounding keys.

That happens before the first key or after the last key on a timeline (dopesheet row). The most often case is after the last key, when creating new keys using a "straight ahead" approach. In that case, Spine used to default to linear. We provide the setting because some users want Bezier (because they want everything Bezier, which may not be the best workflow) or stepped (because they are blocking out their animation, in which case we recommend `Stepped` in the Playback view).

FWIW, the workflow we like the most and recommend is to do as much work as possible before changing your keys to Bezier.

**Comment by bencresty** [comment] 2022-08-08 00:06
That's unfortunate as EVERY keyframe I place is within others. As I normally start with the first and last keyframe to keep them the same, so we can be sure we can 'offset' the animation-layer.
Than I start wondering what's the use of having a default setting?

Also, there seem to be a bug than, because sometimes, at, as it seems, random moments, I suddenly get a STEP-keyframe, while never ever used one in the whole channel AND not set it as a default curve. To me that's odd and unwanted and I would find it hard to believe that's intentional. It's not speeding up the workflow here and causing a lot of re-curving every time, that's for sure.

> FWIW, the workflow we like the most and recommend is to do as much work as possible before changing your keys to Bezier.

Interesting. But how do you judge the animation while working on it if curves still gonna change and make everything change (not fit etc.)?

**Comment by NathanSweet** [comment] 2022-08-08 00:59
You should never get a stepped curve randomly. If you can reproduce it, we'd be happy to fix it!

The default curve setting is mostly for [straight ahead](http://esotericsoftware.com/spine-animating#Straight-ahead) animating, ie setting keys after the last key. Even then I would leave it as linear, as I prefer adjusting Beziers later.

Adjusting Bezier curves is a bit fiddly and tedious. When done too early, there's a higher chance you end up needing to move your keys and adjust your curves again, doubling your Bezier fiddling. It can be more efficient to do as much as possible, then place Beziers where needed. That approach is shown in our [Animating with Spine](https://www.youtube.com/playlist?list=PLwGl7Ikd_6GQ9EpVw2qdvvqgbhjSw7dIj) videos. In general the advice goes for all of animating (and many other things): plan ahead, nail down the most important parts first (eg using pose to pose) because changing them later has a high cost, do details and polish last.

The [Favor tool](https://www.youtube.com/watch?v=RUzXpwwt6hM&lc=UgwvJHvYbLYAuHB5fpd4AaABAg) is great to use after blocking out your most important poses, but before you start using Beziers. Used like that, the Favor tool is similar to using a Bezier to modulate speed between keys, but it's faster/easier and can be applied to many parts of a skeleton at once.

> how do you judge the animation while working on it if curves still gonna change and make everything change (not fit etc.)?

Using [pose to pose](http://esotericsoftware.com/spine-animating#Pose-to-pose). Another [video here](https://www.youtube.com/watch?v=v8quCbt4C-c). In a nutshell, you setup the key poses your animation needs to hit, adjust for timing (very cheap at this point!), add between poses, adjust for timing some more, and then polish.

**Comment by bencresty** [comment] 2022-08-08 09:24
@NathanSweet Thanks for taking the time to write all these tips and adding the videos.

Last week I switched from animating in the graph window to start with the dope sheet using linear curves to set the 'basics'. I'm always working pose to pose btw. And that was a pretty nice and fast workflow change to keep. So guess I'm already doing now what you suggest; first setting linear keyframes and later add and tweak the curves.

BTW I love that Favor tool and also the new Curve panel. Both are extremely useful and speed up the workflow a lot. It's very convenient to be able to always see the curve in full and to store own presets. Also at first I was a little confused about the 'inverted' curve when used on a ease in vs ease out (or visa versa), but I got used to it fast and it's actually very intuitive and useful now. Great design choice.
Have to learn the favor tool better in a day to day practise and making it muscle memory, including the modes it has, but already I had lots of benefits by using it so far and it's definitely a great invention (is it invented by you guys?) which makes a lot of sense!

**Comment by NathanSweet** [comment] 2023-06-11 15:03
The favor tool has been around for some time in other apps, though I'm not sure who did it first. Often it is done as a plugin so it's nice to have first class support for it.

I think we can close this as the way Spine does curve splitting doesn't lend itself well to always giving a specific curve type. If getting a curve type that is unexpected based on the explanation above and that can be reproduced, we'd love to fix and can reopen this or a new issue.

**Closed by NathanSweet** 2023-06-11 15:03 UTC
