### ISSUE TITLE
Export to PNG sequence has artifacts

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-editor#115] opened 2016-09-28 11:06 UTC
See http://esotericsoftware.com/forum/Export-to-PNG-results-in-ghosted-images-7049?p=32702#p32702

See e-mail titled "Bug Report - Export to PNG results in "ghosted" images Search Search this topic" for repro project.

Exporting to PNG using the default settings of the project results in weird artifacts on the users side as well as on my end. On his end (Windows), there's ghosting, on my end, the background isn't transparent (MacOS).

His
![http://i.imgur.com/1cKrLeI.png](http://i.imgur.com/1cKrLeI.png)

Mine
![http://sht.tl/VQEjID](http://sht.tl/VQEjID)

Changing the settings (FPS, etc.) doesn't fix it.

**Comment by badlogic** [comment] 2016-09-28 11:08
Side note: the resulting images are quite big (3405 × 2995), that may be an issue if we render via FBOs.

**Comment by NathanSweet** [comment] 2016-09-28 20:38
Is the problem reproducible for us? Where the problem is reproducible, is it fixed by scaling the root bone to reduce the png sizes? 

We do use FBOs to export (something that is very unlikely to change).

**Comment by NathanSweet** [comment] 2016-11-03 23:22
Replied on forum. Worked fine for me. I expect user's images were too big for his GPU: 4762 x 4665

**Closed** 2016-11-03 23:22 UTC
Labels: bug, editor
