### ISSUE TITLE
Spine crashes when trying to parent a bone from one skeleton to the bone of a different skeleton

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-editor#302] opened 2017-12-11 09:32 UTC
Repro steps:
1. open a project (e.g. spineboy-mesh that already has two skeletons within)
2. select a bone from one skeleton (e.g. the head)
3. press `P` and try to parent it to a bone in the other skeleton (e.g. the other head)
> spine crashes

It should probably be disallowed instead.

**Comment by supersaiyansubtlety** [comment] 2018-08-22 16:14
+1 to fix this. Disallowing would be fine short term, but making it work properly in the future would be great.

**Comment by NathanSweet** [comment] 2018-09-30 21:56
Duplicate of #341, which appears has been fixed.

**Closed by NathanSweet** 2018-09-30 21:56 UTC
Labels: bug, editor, urgent
