### ISSUE TITLE
Weights brush painting

### ISSUE THREAD

**Issue by windship** [EsotericSoftware/spine-editor#139] opened 2016-12-09 08:11 UTC
https://www.2dimensions.com/#nima

I think this kind of weight brush painting will be really comfortable for Spine mesh editor. Currently we have to set each vertex's weight value by dragging control bar and it's so hard to make smooth weight layout. Please consider and add this feature. Thanks.

**Comment by NathanSweet** [comment] 2016-12-09 08:16
Duplicate of #126. This is planned for Spine 3.6, though not by copying Nima. We have our own implementation ideas (and weight painting tools have been around for many, many years).

**Closed by NathanSweet** 2016-12-09 08:16 UTC

**Comment by windship** [comment] 2016-12-09 08:33
Oh sorry, I tried to search the keyword 'paint' but couldn't find the issue. And I just took nima to explain the idea, not say to copy it. BTW sounds great! Can't wait 3.6 to use those features! Thanks!

**Comment by NathanSweet** [comment] 2016-12-09 08:37
No worries. You might check out the [Waffle](https://waffle.io/EsotericSoftware/spine), which makes searching and browsing the issues a bit easier.

We've wanted to improve the mesh tools for a long time, it'll be nice to finally get to it!
